version: 2.1
orbs:
    snyk: snyk/snyk@0.0.8
jobs:
    build-test-publish:
        docker:
            - image: circleci/node:14
        steps:
            - checkout
            - run: sudo npm install semantic-release @semantic-release/exec --save-dev
            - run: npm install
            - run: npx tsc
            - run: npm run test:unit
            - snyk/scan:
                fail-on-issues: true
                monitor-on-build: true
                token-variable: SNYK_TOKEN
            - run: npx semantic-release
    build-test:
        docker:
            - image: circleci/node:14
        steps:
            - checkout
            - run: npm install
            - snyk/scan:
                fail-on-issues: true
                monitor-on-build: false
                token-variable: SNYK_TOKEN
            - run: npx tsc
            - run: npm run test:unit
    build-test-from-fork:
        docker:
            - image: circleci/node:14
        steps:
            - checkout
            - run: npm install
            - run: npx tsc
            - run: npm run test:unit
workflows:
    version: 2
    nightly:
        triggers:
          - schedule:
              cron: "0 0 * * *"
              filters:
                branches:
                  only:
                    - master
        jobs:
            - build-test-publish:
                context: SNYK

    build-test-publish:
        jobs:
            - build-test-publish:
                context: SNYK
                filters:
                    branches:
                        only:
                            - master
    build-test:
        jobs:
            - build-test:
                context: SNYK
                filters:
                    branches:
                        ignore:
                        - master
                        - /pull\/[0-9]+/
            - build-test-from-fork:
                filters:
                    branches:
                        only:
                        - /pull\/[0-9]+/
