name: release-onprem

on:
  #workflow_dispatch:
  push:
    tags:
      - 'onprem-v*'
  
jobs:
  build_test_release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: |
          npm ci
      - name: Test
        id: test
        run: |
          npm run test:unit
      - name: Checkout
        uses: actions/checkout@v3
      - name: generate binary - macos
        run: npx nexe@next dist/index.js -t mac-x64-12.16.2 -o onprem-snyk-user-sync-tool-macos
        run: shasum -a 256 snyk-user-sync-tool-macos > onprem-snyk-user-sync-tool-macos.sha256
      - name: generate binary - linux_x64
        run: npx nexe@next dist/index.js -t linux-x64-12.16.2 -o onprem-snyk-user-sync-tool-linux-x64
        run: shasum -a 256 snyk-user-sync-tool-linux-x64 > onprem-snyk-user-sync-tool-linux-x64.sha256
      - name: generate binary - windows
        run: npx nexe@next dist/index.js -t windows-x64-12.16.2 -o onprem-snyk-user-sync-tool-win.exe
        run: shasum -a 256 snyk-user-sync-tool-win.exe > onprem-snyk-user-sync-tool-win.exe.sha256
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          # Use GH feature to populate the changelog automatically
          generate_release_notes: true
          files: |
            onprem-snyk-user-sync-tool-macos
            onprem-snyk-user-sync-tool-macos.sha256
            onprem-snyk-user-sync-tool-linux-x64
            onprem-snyk-user-sync-tool-linux-x64.sha256
            onprem-snyk-user-sync-tool-win.exe
            onprem-snyk-user-sync-tool-win.exe.sha256
